import = ["~/.config/alacritty/themes/themes/argonaut.toml"]
#import = ["~/.config/alacritty/themes/themes/github_light.toml"]

[font.bold]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"

[window.dimensions]
columns = 125
lines = 35